version: '3.8'

services:
  app:
    build:
      context: .  # Usa la raíz del proyecto como contexto
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app   # Mapea todo el proyecto
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: